# gmake
# This file is automatically generated for client.mk.
# Do not edit. Edit /home/mmadia/.mozconfig instead.
# To create a new .mozconfig file, you can visit,
#   http://webtools.mozilla.org/build/config.cgi

# PATH=/sbin:/bin:/usr/sbin:/usr/local/bin:/usr/bin:/usr/games:/usr/local/sbin:/home/mmadia/bin
MOZ_CO_PROJECT=suite
# --enable-application=suite is used by configure (not client.mk)
MOZ_CO_TAG=MOZILLA_1_8_BRANCH
GLIB_CONFIG=/boot/common/bin/glib-config
LIBIDL_CONFIG=/boot/common/bin/libIDL-config
CVSROOT=:pserver:anonymous@cvs-mirror.mozilla.org:/cvsroot
MOZ_OBJDIR=/moz_obj/suite
# --disable-updater is used by configure (not client.mk)
# --with-bthreads is used by configure (not client.mk)
# --disable-oji is used by configure (not client.mk)
# --disable-svg is used by configure (not client.mk)
# --disable-canvas is used by configure (not client.mk)
# --enable-cpp-rtti is used by configure (not client.mk)
# --disable-tests is used by configure (not client.mk)
# --disable-ipv6 is used by configure (not client.mk)
BUILD_OPT=1
# --enable-optimize=-march=pentium -mcpu=pentiumpro is used by configure (not client.mk)
# --enable-static --disable-shared is used by configure (not client.mk)
# --disable-cpp-exceptions is used by configure (not client.mk)
# --disable-accessibility is used by configure (not client.mk)
